### ISSUE TITLE
lubuntu 18.04 can't start barcode server v 3.0

### ISSUE THREAD

**Issue by jtliaw** [fttx/barcode-to-pc-server#177]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libdns_sd.so.1: æ æ³æå¼å
±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æç®å½
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_barcoduUTvSD/resources/app.asar/node_modules/mdns/lib/dns_sd.js:24:20)
    at Object.<anonymous> (/tmp/.mount_barcoduUTvSD/resources/app.asar/node_modules/mdns/lib/dns_sd.js:39:3)

**Comment by jtliaw** [comment]
I found the problem ubuntu no libavahi-compat-libdnssd1

sudo apt-get install libavahi-compat-libdnssd1

**Comment by fttx** [comment]
Does `sudo apt-get install libavahi-compat-libdnssd1` fix it?
What is your CPU architecture ia32, x64?
