### ISSUE TITLE
appimage not working on linux mint 19.1

### ISSUE THREAD

**Issue by sniff122** [fttx/barcode-to-pc-server#187]
i have set the .appimage file as executable and execute it, i say yes to add it to my menu but it does not load the GUI and just uses a ton of CPU, i have started it in the terminal and got this 
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: libdns_sd.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_barcodQ69Xm1/resources/app.asar/node_modules/mdns/lib/dns_sd.js:24:20)
    at Object.<anonymous> (/tmp/.mount_barcodQ69Xm1/resources/app.asar/node_modules/mdns/lib/dns_sd.js:39:3)`

**Comment by fttx** [comment]
Try to install these packages: avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd1

What is your operating system?

**Comment by sniff122** [comment]
linux mint 19.1, i will try to install these

**Comment by sniff122** [comment]
it now works, but i get 
`*** WARNING *** The program 'barcode-to-pc-server' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'barcode-to-pc-server' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>`
in the console when executing it from the terminal

**Comment by fttx** [comment]
Yes, I know, you can ignore it

**Comment by sniff122** [comment]
ok, thanks
